FinalProjectV1/FinalProjectV1/Models/CarBoard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FinalProjectV1.Models
{
    public class CarBoard
    {
        public List<CarAD> cars { get; set; }

        public List<string> carsProduct { get; set; }

        public List<string> areas { get; set; }
    }
}

FinalProjectV1/FinalProjectV1/Controllers/CarBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProjectV1.Models;
using FinalProjectV1.Helpers;

namespace FinalProjectV1.Controllers
{

    public class CarBoardController : Controller
    {

        // GET: CarBoards
       /* public ActionResult Index()
        {

            List<Advertisement> ads = new List<Advertisement>();
            DBHelper DBhelp = new DBHelper();
            ads = DBhelp.returnAdvertisments();
            List<CarBoard> carB = new List<CarBoard>();

            foreach (var ad in ads)
            {
                Car car = DBhelp.getCarByNumber(ad.CarNumber);
                if (car != null)
                {
                    CarBoard cb = setAndGetCarBoardAd(ad, car);
                    carB.Add(cb);

                }
            }


            return View(carB);
        }*/

        //set and return one advertisment for the car board
        private CarAD setAndGetCarBoardAd(Advertisement ad, Car car)
        {

            if (ad == null && car == null)
                return null;

            if (ad.CarNumber.Equals(car.CarNumber))
            {
                CarAD cb = new CarAD();
                cb.CarNumber = ad.CarNumber;
                cb.SellerName = ad.SellerName;
                cb.Tel = ad.Tel;
                cb.Pic = ad.Pic;
                cb.Description = ad.Description;
                cb.Location = ad.Location;
                cb.DatePublished = ad.DatePublished;
                cb.Price = ad.Price;

                cb.ABS = car.ABS;
                cb.AC = car.AC;
                cb.AirBags = car.AirBags;
                cb.CommericalAlias = car.CommericalAlias;
                cb.EngineCapacity = car.EngineCapacity;
                cb.FuelType = car.FuelType;
                cb.Gaer = car.Gaer;
                cb.KM = car.KM;
                cb.CarColor = car.CarColor;
                cb.PowerWindow = car.PowerWindow;

                cb.Ownership = car.ownerShip;
                cb.ProductName = car.ProductName;
                cb.Roof = car.Roof;
                cb.Yad = car.Yad;
                cb.Year = car.Year;
                return cb;
            }

            return null;
        }

		public ActionResult Index(string productName, string model, int? startYear, int? endYear, string gear, string location, string minPrice, string maxPrice)
        {
            List<CarAD> carsBoard = DBHelper.search(productName, model, startYear, endYear, gear, "", minPrice, maxPrice);
            List<CarAD> tempList = DBHelper.search(productName, model, startYear, endYear, gear, "", minPrice, maxPrice);

            tempList.Sort(delegate (CarAD x, CarAD y)
            {
                return x.FGrade.CompareTo(y.FGrade);
            });

            tempList = tempList.Take(5).ToList();

            CarFeatureExtractor.InitMinMax();

            if (carsBoard != null && carsBoard.Count > 5)
            {
                List<Individual<List<CarAD>>> population = CarsPopulation.create(location, carsBoard, tempList, 100, 5);
                GeneticAlgorithm<List<CarAD>> geneticAlgorithm = new GeneticAlgorithm<List<CarAD>>(300, 2);
                carsBoard = geneticAlgorithm.run(population, startYear, endYear, minPrice, maxPrice).getGenes();
            }
            
            CarBoard cb = new CarBoard();
            cb.cars = carsBoard;
            cb.carsProduct = DBHelper.getCarList();
            cb.carsProduct.Sort();
            cb.areas = DBHelper.getAreas();

            return View(cb);
        }
      
        public JsonResult getCars()
        {
            //DBHelper db = new DBHelper();
            return Json(DBHelper.getCarList());
        }

        public JsonResult getCarModel(string car)
        {
            //DBHelper db = new DBHelper();
            return Json(DBHelper.getCarModelList(car));
        }

        public double calculateGradeOfCar(string carNumber)
        {
            //DBHelper db = new DBHelper();
            List<int> treatmentID = DBHelper.getTreatmentIDs(Int32.Parse(carNumber));

            if (treatmentID==null) 
                return -1;

            List<int> partID = new List<int>();
            List<int> tempID = new List<int>();
            foreach(var id in treatmentID)
            {
                tempID = DBHelper.getPartsIDs(id);

                foreach(var temp in tempID)
                {
                    partID.Add(temp);
                }
            }

            int sum = 0;
            foreach(var id in partID)
            {
                sum += DBHelper.returnPartValueBYID(id);
            }

            return sum;
        }
    }
}

FinalProjectV1/FinalProjectV1/Views/CarBoard/Index.cshtml
@model FinalProjectV1.Models.CarBoard
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="carBoardContainer">
    <h2>לוח רכב</h2>
    <form aasp-controller="CarBoard" asp-action="Index">
        <section class="carBoard" dir="rtl">
            <center>
                <div class="searchBar">
                    <div class="formContainer">
                        <div class="title">יצרן</div>
                        <select class="selectpicker" name="productName" id="prod" onmousedown="if(this.options.length>8){this.size=8;}"  onchange='this.size=0;' onblur="this.size=0;">
                            <option value="">בחר יצרן</option>
                            @foreach (var product in Model.carsProduct)
                            {
                                <option value="@product">@product</option>
                            }
                        </select>
                    </div>
                    <!--<div class="formContainer">
                        <div class="title">דגם</div>
                        <select class="selectpicker" name="model">
                            <option value="">בחר דגם</option>
                            <option value="2614">אוולון</option>
                            <option value="140">אוונסיס</option>
                            <option value="2548">אוונסיס ורסו</option>
                            <option value="1201">אוריס</option>
                            <option value="2336">אייגו (AYGO)</option>
                            <option value="1654">ורסו</option>
                            <option value="1470">יאריס</option>
                            <option value="2344">יאריס הייבריד</option>
                            <option value="1525">סולרה קבריולט</option>
                            <option value="143">סטארלט</option>
                            <option value="1046">פריוס</option>
                            <option value="2527">פריוס C</option>
                            <option value="2376">פריוס פלוס</option>
                            <option value="146">קאמרי</option>
                            <option value="1428">קורולה</option>
                        </select>
                    </div>-->
                    <div class="formContainer">
                        <div class="title">הילוכים</div>
                        <select class="selectpicker" name="gear">
                            <option value="">הילוכים</option>
                            <option value="אוטומטי">אוטומטי</option>
                            <option value="ידני">ידני</option>
                        </select>
                    </div>
                    <div class="formContainer">
                        <div class="title">אזור</div>
                        <select class="selectpicker" name="location">
                            <option value="">בחר אזור</option>
                            @foreach (var area in Model.areas)
                            {
                                <option value="@area">@area</option>
                            }
                        </select>
                    </div>
                    </br>
                    <div class="formContainer">
                        <div class="title">משנה</div>
                        <select class="selectpicker" name="startYear">
                            <option value="">החל משנת</option>
                            <option value="2017">2017</option>
                            <option value="2016">2016</option>
                            <option value="2015">2015</option>
                            <option value="2014">2014</option>
                            <option value="2013">2013</option>
                            <option value="2012">2012</option>
                            <option value="2011">2011</option>
                            <option value="2010">2010</option>
                            <option value="2009">2009</option>
                            <option value="2008">2008</option>
                            <option value="2007">2007</option>
                            <option value="2006">2006</option>
                            <option value="2005">2005</option>
                            <option value="2004">2004</option>
                            <option value="2003">2003</option>
                            <option value="2002">2002</option>
                            <option value="2001">2001</option>
                            <option value="2000">2000</option>
                            <option value="1999">1999</option>
                            <option value="1998">1998</option>
                            <option value="1997">1997</option>
                            <option value="1996">1996</option>
                            <option value="1995">1995</option>
                        </select>
                    </div>
                    <div class="formContainer">
                        <div class="title">עד שנה</div>
                        <select class="selectpicker" name="endYear">
                            <option value="">עד שנת</option>
                            <option value="2017">2017</option>
                            <option value="2016">2016</option>
                            <option value="2015">2015</option>
                            <option value="2014">2014</option>
                            <option value="2013">2013</option>
                            <option value="2012">2012</option>
                            <option value="2011">2011</option>
                            <option value="2010">2010</option>
                            <option value="2009">2009</option>
                            <option value="2008">2008</option>
                            <option value="2007">2007</option>
                            <option value="2006">2006</option>
                            <option value="2005">2005</option>
                            <option value="2004">2004</option>
                            <option value="2003">2003</option>
                            <option value="2002">2002</option>
                            <option value="2001">2001</option>
                            <option value="2000">2000</option>
                            <option value="1999">1999</option>
                            <option value="1998">1998</option>
                            <option value="1997">1997</option>
                            <option value="1996">1996</option>
                            <option value="1995">1995</option>
                        </select>
                    </div>
                    <div class="formContainer">
                        <input type="text" class="form-control" name="minPrice" placeholder="ממחיר">
                    </div>
                    <input type="text" class="form-control" name="maxPrice" placeholder="עד מחיר">
                    <input type="submit" value="חפש" class="btn btn-default"/>
                </div>
            </center>
        </section>
    </form>

    </hr>

    <ul class="messagesBoard" id="messagesBoardList">
        <li class="panelHeader row">
            <div class="col-xs-1"><img src="~/images/img3.png" /></div>
            <div class="col-xs-4">יצרן-דגם</div>
            <div class="col-xs-1">נפח</div>
            <div class="col-xs-1">שנה</div>
            <div class="col-xs-1">יד</div>
            <div class="col-xs-1">הילוכים</div>
            <div class="col-xs-1">מחיר</div>
            <div class="col-xs-2">איזור</div>
            <!--<div class="col-xs-1"><img src="~/images/img5.png" /></div>
            <div class="col-xs-2">תאריך</div>-->
        </li>

@if (Model.cars != null)
{
        foreach (var item in Model.cars)
        {


            <li class="panel row">
                <a href="javascript:void(0)" class="btnCollapse row collapsed" data-target="#@item.CarNumber" data-toggle="collapse" data-parent="#messagesBoardList">
                    <div class="col-xs-1"><img src="~/images/img2.png" /></div>
                    <div class="col-xs-4">@item.ProductName @item.CommericalAlias</div>
                    <div class="col-xs-1">@item.EngineCapacity</div>
                    <div class="col-xs-1">@item.Year</div>
                    <div class="col-xs-1">@item.Yad</div>
                    <div class="col-xs-1">@item.Gaer</div>
                    <div class="col-xs-1">@item.Price</div>
                    <div class="col-xs-2">@item.Location</div>
                    <!--<div class="col-xs-1"><img src="~/images/img4.png" /></div>
                    <div class="col-xs-2">@*@item.DatePublished.ToShortDateString()*@</div>-->
                </a>
                <div class="messageDropdown row collapse" id="@item.CarNumber">
                    <div class="col-sm-6 descMessage">
                        <ul class="carDeatilesList list-group">
                            <li class="title">פרטי הרכב</li>
                            <li class="list-group-item"><strong>יצרן:</strong>@item.ProductName</li>
                            <li class="list-group-item"><strong>דגם:</strong>@item.CommericalAlias</li>
                            <li class="list-group-item"><strong>נפח:</strong>@item.EngineCapacity</li>
                            <li class="list-group-item"><strong>שנה:</strong>@item.Year</li>
                            <li class="list-group-item"><strong>יד:</strong>@item.Yad</li>
                            <li class="list-group-item"><strong>הילוכים:</strong>@item.Gaer</li>
                            <li class="list-group-item"><strong>בעלות:</strong>@item.Ownership</li>
                            <li class="list-group-item"><strong>ק"מ:</strong>@item.KM</li>
                            <li class="list-group-item">
                                <div class="row ">
                                    <div class="col-xs-6 secondaryListContainer">
                                        <ul class="secondaryList">
                                            <li>ABS</li>
                                            <li>גג שמש</li>
                                            <li>כריות אוויר</li>
                                            <li>חלונות חשמליים</li>
                                            <li>מזגן</li>
                                        </ul>
                                    </div>
                                    <div class="col-xs-6 pika">
                                        <ul>
                                            <li>@item.ABS</li>
                                            <li>@item.Roof</li>
                                            <li>@item.AirBags</li>
                                            <li>@item.PowerWindow</li>
                                            <li>@item.AC</li>
                                        </ul>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-sm-6 descMessage">
                        <div class="carDeatiles">
                            <div class="title">תמונה</div>
                            <div class="pic">
                                <img src=@item.Pic />
                            </div>
                        </div>
                        <div class="carDeatiles">
                            <div class="title">תיאור/תוספות</div>
                            <div class="content">
                                <p>
                                    @item.Description
                                </p>
                            </div>
                        </div>
                        <div class="carDeatiles">
                            <div class="title">יצירת קשר</div>
                            <div class="content">
                                <div><strong>שם המוכר:</strong>@item.SellerName</div>
                                <div><strong>טלפון:</strong>@item.Tel</div>
                                <form controller="History" action="History/History">
                                    <section class="history" dir="rtl">
                                        <div hidden class="formContainer">
                                            <input hidden class="form-control" type="hidden" name="carNumber" value="@item.CarNumber" />
                                        </div>
                                        <div class="formContainer">
                                            <text>סיסמה זמנית: </text>
                                            <input class="form-control" type="password" name="password" /><!--<strong>:סיסמה זמנית</strong>-->
                                        </div>
                                        <div hidden class="formContainer">
                                            <input hidden class="form-control" type="hidden" name="isOwner" value="False" />
                                        </div>
                                        <div>
                                            <input type="submit" value="שלח" class="btn btn-default" />
                                        </div>
                                    </section>
                                </form>  
                            </div>
                        </div>
                    </div>
                </div>
            </li>


        }
}
    </ul>
</div>